main: com.shadowolfyt.zander.ZanderMain
name: zander
version: 1.0
author: Ben Robson
api-version: 1.13
softdepend:
- TitleAPI

commands:
  heal:
    description: Heal a user back to full health.
    usage: /heal [target]
  feed:
    description: Satisfy a users hunger.
    usage: /feed [target]
  starve:
    description: Deprives users of their hunger.
    usage: /starve [target]
  gma:
    description: Changes players gamemode to adventure.
    usage: /gma [target]
    aliases: [adventure, a]
  gmc:
    description: Changes players gamemode to creative.
    usage: /gmc [target]
    aliases: [creative, c]
  gms:
    description: Changes players gamemode to survival.
    usage: /gms [target]
    aliases: [survival, s]
  gmsp:
    description: Changes players gamemode to spectator.
    usage: /gmsp [target]
    aliases: [spectator, sp]
  fly:
    description: Allows players to fly.
    usage: /fly [target]
  profile:
    description: Display your profile stats.
    usage: /profile
  whitelist:
    description: Whitelist Command.
    usage: /whitelist
    aliases: [wl]
  jukebox:
    description: Jukebox Command.
    usage: /jukebox
    aliases: [play]
  punish:
    description: Punish Command.
    usage: /punish [target]
    aliases: [p]
  freeze:
    description: Freeze Command.
    usage: /freeze [target]
  kick:
    description: Kick Command.
    usage: /kick [target] [reason]
  ban:
    description: Ban Command.
    usage: /ban [target] [reason]
  pardon:
    description: Pardon/Unban a user from the server.
    usage: /pardon [target]
    aliases: [unban]
  discord:
    description: Discord command.
    usage: /discord
  difficulty:
    description: Difficulty command.
    usage: /difficulty
  rules:
    description: Rules command.
    usage: /rules

permissions:
  zander.heal:
    default: op
  zander.feed:
    default: op
  zander.starve:
    default: op
  zander.pardon:
    default: op
  zander.survival:
    default: op
  zander.creative:
    default: op
  zander.adventure:
    default: op
  zander.spectator:
    default: op
  zander.fly:
    default: op
  zander.whitelist:
    default: op
  zander.jukebox:
    default: op
  zander.punish:
    default: op
  zander.freeze:
    default: op
  zander.kick:
    default: op
  zander.ban:
    default: op
  zander.punishnotify:
    default: op
  zander.difficulty:
    default: op
